version: 2
enable-beta-ecosystems: true
updates:
  # Use npm ecosystem for Bun compatibility
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "npm"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "Zaid-amker"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
